import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiFillGithub, AiFillInstagram, AiFillLinkedin } from "react-icons/ai";
import Image from "next/image";
import web1 from "../public/porto-1.png";
import code from "../public/code.svg";
import profile from "../public/profile.png";
import design from "../public/design.svg";
import consul from "../public/consulting.svg";
import { useState } from "react";

export default function Home() {
  const [getDarkMode, setDarkMode] = useState(false);
  return (
    <div className={getDarkMode ? "dark" : ""}>
      <Head>
        <title>Personal Web</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900">
        <section className=" min-h-screen">
          <nav className="py-10 mb-12 flex justify-between">
            <h1 className="text-xl dark:text-slate-300">Beby Kurniawan</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!getDarkMode)}
                  className="cursor-pointer text-2xl dark:text-slate-300"
                />
              </li>
              <li>
                <a
                  href=""
                  className="drop-shadow-md  bg-gradient-to-r from-cyan-500 to-teal-400 text-white px-4 py-2 rounded-md ml-7"
                >
                  Contact
                </a>
              </li>
            </ul>
          </nav>
          {/* HERO SECTION */}
          <div className="text-center p-10">
            <h2 className="text-4xl text-cyan-500 py-2 font-bold md:text-5xl lg:text-6xl">
              Beby Kurniawan
            </h2>
            <h3 className="text-xl py-2 md:text-2xl lg:text-3xl dark:text-white">
              Junior Frontend Developer
            </h3>
            <p className="text-md pt-4 leading-7 text-slate-800 text-center md:text-lg max-w-lg mx-auto dark:text-slate-300">
              Lorem ipsum, dolor sit amet consectetur adipisicing elit. Quas
              omnis architecto at iusto optio. Assumenda.
            </p>
          </div>
          <div className=" text-4xl flex justify-center gap-12">
            <AiFillGithub className="text-slate-800 hover:text-slate-600 dark:text-slate-300 dark:hover:text-slate-200" />
            <AiFillInstagram className="text-slate-800 hover:text-slate-600 dark:text-slate-300 dark:hover:text-slate-200" />
            <AiFillLinkedin className="text-slate-800 hover:text-slate-600 dark:text-slate-300 dark:hover:text-slate-200" />
          </div>
          <div className="w-80 drop-shadow-lg mx-auto md:w-[340px]">
            <Image src={profile}/>
          </div>
        </section>
        {/* HERO SECTION */}

        {/* SERVICE SECTION */}
        <section>
          <div>
            <h3 className="text-3xl py-2 dark:text-white">Service</h3>
            <p className=" text-md leading-8 text-gray-800 dark:text-slate-300 lg:max-w-2xl">
              Lorem ipsum dolor sit, amet consectetur adipisicing elit.
              Reprehenderit id cumque officia. Fugit, deserunt vel molestiae,
              provident dicta explicabo a cupiditate quaerat omnis hic veniam?
            </p>
          </div>
          <div className="lg:flex gap-10">
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-slate-100">
              <Image src={design} width={80} className="mx-auto" />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Interesting Design
              </h3>
              <p className="text-gray-800">
                creating beautiful web designs according to your needs
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-slate-100">
              <Image src={consul} width={80} className="mx-auto" />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Interesting Design
              </h3>
              <p className="text-gray-800">
                creating beautiful web designs according to your needs
              </p>
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-slate-100">
              <Image src={code} width={75} className="mx-auto" />
              <h3 className="text-lg font-medium pt-8 pb-2">
                Interesting Design
              </h3>
              <p className="text-gray-800">
                creating beautiful web designs according to your needs
              </p>
            </div>
          </div>
        </section>
        {/* SERVICE SECTION */}
        <section>
          <div>
            <h3 className="text-3xl py-1 dark:text-white">Portofolio</h3>
            <p className="leading-7 text-md text-gray-800 py-1 dark:text-slate-300 lg:max-w-2xl">
              Lorem, ipsum dolor sit amet consectetur adipisicing elit. Placeat
              quaerat vitae exercitationem, ratione voluptate sit eos laudantium
              velit quidem, voluptatum recusandae repellat doloribus. Neque
              eligendi blanditiis minima sapiente quas doloremque.
            </p>
          </div>
          <div className="flex flex-col py-10 gap-10 lg:flex-row lg:flex-wrap">
            <div className="basis-1/3 flex-1">
              <Image
                src={web1}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web1}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web1}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web1}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web1}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
            <div className="basis-1/3 flex-1">
              <Image
                src={web1}
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
              />
            </div>
          </div>
        </section>
      </main>
    </div>
  );
}
